In [1]:
import torch

x = torch.Tensor([3, 5])
y = torch.Tensor([2, 1])

print(x*y)

tensor([6., 5.])


In [2]:
x = torch.zeros([2,5])

In [3]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])

In [6]:
y

tensor([[0.0659, 0.9733, 0.8354, 0.8647, 0.9200],
        [0.5078, 0.6182, 0.7189, 0.8218, 0.4041]])

In [7]:
y.view([1,10])

tensor([[0.0659, 0.9733, 0.8354, 0.8647, 0.9200, 0.5078, 0.6182, 0.7189, 0.8218,
         0.4041]])

In [8]:
y

tensor([[0.0659, 0.9733, 0.8354, 0.8647, 0.9200],
        [0.5078, 0.6182, 0.7189, 0.8218, 0.4041]])

In [9]:
y = y.view([1,10])